// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsIwsnLR2rP1xMqR_A_yoi4x4udOsKhZk',
    appId: '1:704942263251:web:0189482d607ef1e4ecfd26',
    messagingSenderId: '704942263251',
    projectId: 'banking-app-9a386',
    authDomain: 'banking-app-9a386.firebaseapp.com',
    storageBucket: 'banking-app-9a386.firebasestorage.app',
    measurementId: 'G-KCESBJ3BS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHefD8TUzRNZlfdsu_WqXY3UERtBUdJ8E',
    appId: '1:704942263251:android:554ae1e859bb0108ecfd26',
    messagingSenderId: '704942263251',
    projectId: 'banking-app-9a386',
    storageBucket: 'banking-app-9a386.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAsWC-vulG7ncGNf-QMfDorikR1s9q_ys',
    appId: '1:704942263251:ios:29c2e3de8b196df5ecfd26',
    messagingSenderId: '704942263251',
    projectId: 'banking-app-9a386',
    storageBucket: 'banking-app-9a386.firebasestorage.app',
    iosBundleId: 'com.example.bankingMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAsWC-vulG7ncGNf-QMfDorikR1s9q_ys',
    appId: '1:704942263251:ios:29c2e3de8b196df5ecfd26',
    messagingSenderId: '704942263251',
    projectId: 'banking-app-9a386',
    storageBucket: 'banking-app-9a386.firebasestorage.app',
    iosBundleId: 'com.example.bankingMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsIwsnLR2rP1xMqR_A_yoi4x4udOsKhZk',
    appId: '1:704942263251:web:c3c272f8e9163bb1ecfd26',
    messagingSenderId: '704942263251',
    projectId: 'banking-app-9a386',
    authDomain: 'banking-app-9a386.firebaseapp.com',
    storageBucket: 'banking-app-9a386.firebasestorage.app',
    measurementId: 'G-HW4504T4RX',
  );
}
